### PR TITLE
2015 04 tb map listing

### PR DESCRIPTION
**Pull request by MagdaN**

### CODE REVIEW

**Comment by MagdaN** [comment]
@local-girl : applied filters should also be added to map-list. I tried that by adding a dummy method that removes an element from the list - it works, but the width on the list element somehow shrinks. Do you have any  idea, why?

**Comment by local-girl** [comment]
I'm happy to look at this now...

**Comment by MagdaN** [comment]
Can be reviewed

**Comment by xi** [comment]
continued in #1026

**Pull request closed without merging**
