### PR TITLE
Change image sizes as required by the designers

### PR DESCRIPTION
**Pull request by ChristianSi**
Detail and thumbnail view now have totally different ratios, but that's just now they want it.

### CODE REVIEW

**Comment by nidico** [comment]
Err, thumbnail and detail look pretty much reversed.

**Comment by ChristianSi** [comment]
Dammit, feel free to fix directly on master.

**Comment by nidico** [comment]
Done in 193b3006b0c4ee209dfbe1556ce064878a08d380.

**Comment by local-girl** [comment]
Apologies !!

**Comment by ChristianSi** [comment]
@local-girl Never mind, it was my mistake.

Thanks for catching it, @nidico!

**Pull request merged**
