### PR TITLE
Add build and publish to travis

### PR DESCRIPTION
**Pull request by slomo**
- build all platforms not only mercator
- use travis to trigger build for master and releases

### CODE REVIEW

**Comment by slomo** [comment]
Enables some of the features of #958 which I would like to rather split up into this one and two others pull requests (one with coverage the other changing to firefox for acceptance tests)

**Comment by nidico** [comment]
Any idea why didn't travis didn't run for this PR? (or do I just not find it?)

**Comment by nidico** [comment]
@slomo: Does it work for you?

**Comment by slomo** [comment]
@nidico I think it where some stuiped errors by me I forget to run the last version through http://lint.travis-ci.org/

**Comment by slomo** [comment]
Also I replaced the after_success by a more secure version (maybe also a bit more obvious)

**Comment by nidico** [comment]
Can you please rebase onto / merge in master? The test suite passes on master in the meantime :)

**Comment by nidico** [comment]
LGTM.

**Pull request merged**
