### PR TITLE
2015 05 cc ui tidy+1

### PR DESCRIPTION
**Pull request by local-girl**
Some general UI tidy based on UI tasks in https://pad.liqd.net/p/meinberlinIssues

### CODE REVIEW

**Comment by local-girl** [comment]
It would be nice for people to be able to get back home...

**Comment by xi** [comment]
The map pins look strange. They have a tiny outline that looks really weird if they are small.

**Comment by xi** [comment]
Apart from my two comments this looks goog.

**Comment by local-girl** [comment]
Review ?

**Comment by xi** [comment]
LGTM.

**Pull request merged**
