### PR TITLE
Add mercator badge filters

### PR DESCRIPTION
**Pull request by xi**

### CODE REVIEW

**Comment by xi** [comment]
@MagdaN reported that she had a blank screen when testing this. That is probably cause by the issue that is fixed in #1297.

**Comment by xi** [comment]
I just noticed that bades have the `ITitle` sheet. Maybe it's better to use those rather than defining new translatable strings?

**Comment by MagdaN** [comment]
@xi I had to merge master to get it working again - now it works fine

**Comment by MagdaN** [comment]
@xi: how would you do translations, then?

**Pull request merged**
