### PR TITLE
2015 03 mn add maps

### PR DESCRIPTION
**Pull request by MagdaN**

### CODE REVIEW

**Comment by MagdaN** [comment]
This should work when using the buildout-meinberlin.cfg for buildout and open Link: http://localhost:6551/embed/map-input?id=mymap&lng=13.3592486393&lat=52.5011278698&height=500

**Comment by MagdaN** [comment]
I am still working on this

**Comment by xi** [comment]
I did some refactoring. Some notable changes:

-  `l.Map` can also take a `DOMElement` as first argument. I think this is preferable because ids need to be unique.
-  I added types. That required some small changes, e.g. I had to rename `L` to `leaflet`.

**Comment by xi** [comment]
LGTM.

**Pull request merged**
