### PR TITLE
Revert "Skip header validation if authentication is done by Thentos"

### PR DESCRIPTION
**Pull request by fhartwig**
Reverts liqd/adhocracy3.mercator#1778

As @ChristianSi pointed out, that PR was just masking another problem (#1798) and would actually break things at a later point. Sorry for that.

### CODE REVIEW

**Comment by pallix** [comment]
So we can close it?

**Comment by fhartwig** [comment]
@pallix I'm not sure what you mean. #1778 was merged, and this PR reverts those changes.

**Comment by pallix** [comment]
Ok sorry, I misunterstood something.

**Comment by joka** [comment]
> Reverts liqd/adhocracy3.mercator#1778
> 
> As @ChristianSi pointed out, that PR was just masking another problem (#1798) and would actually break things at a later point. Sorry for that.

I comment to https://github.com/liqd/adhocracy3.mercator/pull/1778#issuecomment-151094514

**Pull request merged**
