### PR TITLE
Add migration script for the mercator process

### PR DESCRIPTION
**Pull request by pallix**
I get this stacktrace when trying to evolve an old db:

```
Executing evolution step adhocracy_core.evolution.evolve1_add_title_sheet_to_pools
Traceback (most recent call last):
  File "./bin/sd_evolve", line 112, in <module>
    sys.exit(substanced.scripts.evolve.main())
  File "/home/alphonse/projects/adhocracy3.mercator/src/substanced/substanced/scripts/evolve.py", line 83, in main
    complete = manager.evolve(latest)
  File "/home/alphonse/projects/adhocracy3.mercator/src/substanced/substanced/evolution/__init__.py", line 75, in evolve
    func(self.context)
  File "/home/alphonse/projects/adhocracy3.mercator/src/adhocracy_core/adhocracy_core/evolution/__init__.py", line 79, in evolve1_add_title_sheet_to_pools
    migrate_new_sheet(root, IBasicPool, ITitle, IPool,
  File "/home/alphonse/projects/adhocracy3.mercator/src/adhocracy_core/adhocracy_core/evolution/__init__.py", line 46, in migrate_new_sheet
    resources = pool.get(query)['elements']
  File "/home/alphonse/projects/adhocracy3.mercator/src/adhocracy_core/adhocracy_core/sheets/pool.py", line 38, in get
    return super().get(params)
  File "/home/alphonse/projects/adhocracy3.mercator/src/adhocracy_core/adhocracy_core/sheets/__init__.py", line 97, in get
    appstruct.update(self._get_reference_appstruct(query))
  File "/home/alphonse/projects/adhocracy3.mercator/src/adhocracy_core/adhocracy_core/sheets/pool.py", line 66, in _get_reference_appstruct
    result = self._catalogs.search(query)
  File "/home/alphonse/projects/adhocracy3.mercator/src/adhocracy_core/adhocracy_core/catalog/__init__.py", line 48, in search
    elements = self._search_elements(query)
  File "/home/alphonse/projects/adhocracy3.mercator/src/adhocracy_core/adhocracy_core/catalog/__init__.py", line 91, in _search_elements
    elements = index_query.execute(resolver=None)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/hypatia-0.3-py3.4-linux-x86_64.egg/hypatia/query/__init__.py", line 448, in execute
    resolver=resolver
  File "/home/alphonse/projects/adhocracy3.mercator/src/substanced/substanced/catalog/indexes.py", line 65, in resultset_from_query
    docids = query._apply(names)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/hypatia-0.3-py3.4-linux-x86_64.egg/hypatia/query/__init__.py", line 568, in _apply
    result = queries[0]._apply(names)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/hypatia-0.3-py3.4-linux-x86_64.egg/hypatia/query/__init__.py", line 268, in _apply
    return self.index.applyAll(self._get_value(names))
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/hypatia-0.3-py3.4-linux-x86_64.egg/hypatia/keyword/__init__.py", line 110, in applyAll
    return self.apply({'query': values, 'operator': 'and'})
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/hypatia-0.3-py3.4-linux-x86_64.egg/hypatia/keyword/__init__.py", line 284, in apply
    return self.search(query, operator=operator)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/hypatia-0.3-py3.4-linux-x86_64.egg/hypatia/keyword/__init__.py", line 255, in search
    docids = self._fwd_index.get(word, self.family.IF.Set())
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/ZODB-4.1.0-py3.4.egg/ZODB/Connection.py", line 871, in setstate
    self._setstate(obj)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/ZODB-4.1.0-py3.4.egg/ZODB/Connection.py", line 925, in _setstate
    self._reader.setGhostState(obj, p)
  File "/home/alphonse/projects/adhocracy3.mercator/eggs/ZODB-4.1.0-py3.4.egg/ZODB/serialize.py", line 635, in setGhostState
    obj.__setstate__(state)
TypeError: Object has default comparison

```

### CODE REVIEW

**Comment by pallix** [comment]
Got this output when debugging bevore `self._reader.setGhostState(obj, p)` 

```
>>> obj                                                                                                                        
<BTrees.OOBTree.OOBTree object at 0x7f8cedeec268>   

>>> p
b'\x80\x03cBTrees.OOBTree\nOOBTree\nq\x00.\x80\x03(C\x08\x00\x00\x00\x00\x00\x00\x01hq\x01cBTrees.OOBTree\nOOBucket\nq\x02\x86 
q\x03Qchypatia.interfaces\nIIndex\nq\x04C\x08\x00\x00\x00\x00\x00\x00\x0bxq\x05h\x02\x86q\x06Qcadhocracy_core.sheets.name\nINa 
me\nq\x07C\x08\x00\x00\x00\x00\x00\x00\x01iq\x08h\x02\x86q\tQcadhocracy_core.interfaces\nIServicePool\nq\nC\x08\x00\x00\x00\x0 
0\x00\x00\x0b\x98q\x0bh\x02\x86q\x0cQtq\rh\x01h\x02\x86q\x0eQ\x86q\x0f.'
```
p is the pickle value.

In the next call

```
def setGhostState(self, obj, pickle):                                                                                    
          state = self.getState(pickle) 
          obj.__setstate__(state)
```

```self.getState(pickle)``` raises ```Couldn't load state for BTrees.OOBTree.OOBucket 0x0169```

**Comment by pallix** [comment]
Changed the migration code but I cannot really test it, I get the same error

**Comment by pallix** [comment]
Migration is running correctly after the fix

**Comment by pallix** [comment]
Ah... I get an error:

```RuntimeConfigurationError: Cannot find post_pool with interface or service name badge_assignments for context /mercator/b3530/VERSION_0000001.; time: 2015-06-10 16:42:49,064"``

Something still missing.

**Comment by pallix** [comment]
I'll do the other migration in another PR.

**Comment by joka** [comment]
lgtm, migration testet with old mercator database.
@pallix  can you have quick look at my changes and then merge?

**Pull request merged**
