### PR TITLE
2015 03 mn create mein berlin list view

### PR DESCRIPTION
**Pull request by MagdaN**

### CODE REVIEW

**Comment by MagdaN** [comment]
I am still working on that

**Comment by MagdaN** [comment]
This is ready for review. When this is done the css styles can be applied - should that happen in the same branch?

**Comment by MagdaN** [comment]
I implemented the base functionality - for review check: /embed/mein-berlin-kiezkassen-proposal-list

**Comment by xi** [comment]
Looks good to me. I did some refactoring. Feel free to merge.

**Pull request merged**
