### PR TITLE
Add travis CI

### PR DESCRIPTION
**Pull request by nidico**
This adds a simple Travis configuration, which automatically builds `adhocracy.mercator` and runs the test suite on each `git push` or github pull request.

### CODE REVIEW

**Comment by nidico** [comment]
Unfortunately, some comment tests (`test_edit_twice` or `test_reply_other_user`) still randomly fail...

**Comment by joka** [comment]
> Unfortunately, some comment tests (test_edit_twice, test_edit_other_user, test_reply_other_user) still randomly fail...

Travis does not make sense without stable tests
We should mark all unstable tests "x-fail" until we solve these issues.

**Comment by nidico** [comment]
> We should mark all unstable tests "x-fail" until we solve these issues.

Done.

**Comment by nidico** [comment]
> We also support python 3.3.

Why? Debian stable has Python 3.2, the next stable will have Python 3.4. Ubuntu LTS has Python 3.4... Let's save some power in the Travis data center...

**Comment by nidico** [comment]
All is well :)

**Pull request merged**
