### PR TITLE
Changing requested funding filter to total budget

### PR DESCRIPTION
**Pull request by local-girl**
requires reset of database and restart of server to see in full effect. I left references to requested_funding in just in case..? Just removed from frontend

### CODE REVIEW

**Comment by xi** [comment]
Looks good (and also surprisingly few changes to the code). However, the acceptance tests need to be adapted. Will you do it or should I?

**Comment by local-girl** [comment]
I'll do it

**Comment by xi** [comment]
Thanks

**Comment by local-girl** [comment]
Fixed tests

**Comment by xi** [comment]
merged master again because the acceptance tests were broken.

**Comment by xi** [comment]
LGTM.

**Pull request merged**
