### PR TITLE
Use protocol relative URLs in minified socialshare (fixes #865)

### LINKED ISSUE #865: Minified version of socialshare loads iframes through http
This is due to the minified version of `jquery.socialshareprivacy` not using protocol relative urls.

### PR DESCRIPTION
**Pull request by nidico**

### CODE REVIEW

**Comment by nidico** [comment]
Merging myself cause "urgent".

**Comment by xi** [comment]
Do I understand correctly that you simple re-minifed the updated source file?

**Comment by nidico** [comment]
yes.

**Comment by xi** [comment]
LGTM.

**Pull request merged**
