### PR TITLE
Raise error if /batch tries to invoke subrequests outside script_name

### PR DESCRIPTION
**Pull request by nidico**
If this would have been there, #1102 would have been much easier to solve.

### CODE REVIEW

**Comment by joka** [comment]
Comment what this is about  and ' pragam: no cover is missing or just add add a test case

**Comment by joka** [comment]
one pyunit test is also failing

**Comment by nidico** [comment]
Rebased and

> Comment what this is about and ... add a test case

done.

**Comment by joka** [comment]
@nidico  can you merge master?

**Comment by nidico** [comment]
> @nidico can you merge master?

rebased.

**Pull request merged**
