### PR TITLE
send coverage reports to coveralls

### PR DESCRIPTION
**Pull request by joka**

### CODE REVIEW

**Comment by joka** [comment]
the build is broken, so cannot test if this actually works.

**Comment by ChristianSi** [comment]
Nice!

**Comment by nidico** [comment]
For the reference: I disabled the "add comments to pull requests" feature, as I find it rather annoying, and the information is already in the "Merge"-Box.

**Comment by nidico** [comment]
Also, I fixed the coveralls badge in the README in 56a5d39f4b593f762287712bb3fa1619db3a0359.

**Pull request merged**
