### PR TITLE
add script to  cleanup stale login data objects

### PR DESCRIPTION
**Pull request by joka**
Internal API Extensions:

- add  function resource "is_older_than"
- add method delete_expired_tokens to authentication  token manager
- add method get_users to interate all users resources to UserAndRoles Finder
- add funtion 'delete_password_resets' to remove not used reset resources.
- add function 'delete_not_activated_users' to remove not activated users.
- add script 'delete_stale_login_data'

### CODE REVIEW

**Comment by pallix** [comment]
See comments above, linked to the commits, for my code review.

**Comment by pallix** [comment]
`TestValidateActivationPathUnitTest.test_found_but_expired` is failing

**Comment by joka** [comment]
@pallix  all test pass, comments fixed, can you merge?

**Comment by pallix** [comment]
You did replace print by logging a while ago in the scripts. We need to discuss this. Merging anyway.

**Pull request merged**
