### PR TITLE
Create pcompass workbench

### PR DESCRIPTION
**Pull request by xi**
*depends on #1658*

This adds a workbench and context for pcompass. It uses the standard proposal. This is all havily based on meinberlin.

Stuff that is still to do:

-   (maybe) move proposal package to core
-   styling, e.g. move styles from meinberlin to core
-   change wording from "proposal" to "request"

### CODE REVIEW

**Comment by local-girl** [comment]
Hey I'm unable to run the import_resources script any more since pulling from master, @nidico tried said its something to do with https://github.com/liqd/adhocracy3.mercator/commit/4d7e7f0ac66aa1a34a958422ea3894dc4e0d9bf7 but I thin that's been updated already - can someone have a look please? Blocked.

```
(13552) Blob dir /home/caroline/www/adhocracy3/var/blobs/ has insecure mode setting
(13552) Blob dir /home/caroline/www/adhocracy3/var/blobs/ has insecure mode setting
Problem connecting to Websocket server: ConnectionRefusedError: [Errno 111] Connection refused
Problem connecting to Websocket server: ConnectionRefusedError: [Errno 111] Connection refused
Problem connecting to Websocket server: ConnectionRefusedError: [Errno 111] Connection refused
/home/caroline/www/adhocracy3/eggs/multipledispatch-0.4.8-py3.4.egg/multipledispatch/dispatcher.py:24: AmbiguityWarning: 
Ambiguities exist in dispatched function create_arbitrary_filter_node

The following signatures may result in ambiguous behavior:
	[ReferenceIndex, object, str], [object, str, str]
	[ReferenceIndex, object, str], [object, datetime, str]
	[ReferenceIndex, object, str], [object, bool, str]
	[ReferenceIndex, object, str], [object, int, str]


Consider making the following additions:

@dispatch(ReferenceIndex, str, str)
def create_arbitrary_filter_node(...)

@dispatch(ReferenceIndex, datetime, str)
def create_arbitrary_filter_node(...)

@dispatch(ReferenceIndex, bool, str)
def create_arbitrary_filter_node(...)

@dispatch(ReferenceIndex, int, str)
def create_arbitrary_filter_node(...)
  warn(warning_text(dispatcher.name, ambiguities), AmbiguityWarning)
/home/caroline/www/adhocracy3/eggs/multipledispatch-0.4.8-py3.4.egg/multipledispatch/dispatcher.py:24: AmbiguityWarning: 
Ambiguities exist in dispatched function create_arbitrary_filter_node

The following signatures may result in ambiguous behavior:
	[ReferenceIndex, object, str], [object, bool, str]
	[ReferenceIndex, object, str], [object, datetime, str]
	[ReferenceIndex, object, str], [object, str, str]
	[ReferenceIndex, object, str], [object, int, str]


Consider making the following additions:

@dispatch(ReferenceIndex, bool, str)
def create_arbitrary_filter_node(...)

@dispatch(ReferenceIndex, datetime, str)
def create_arbitrary_filter_node(...)

@dispatch(ReferenceIndex, str, str)
def create_arbitrary_filter_node(...)

@dispatch(ReferenceIndex, int, str)
def create_arbitrary_filter_node(...)
  warn(warning_text(dispatcher.name, ambiguities), AmbiguityWarning)
Cannot autosync/autoreindex catalog due to unfinished evolve steps
INFO:adhocracy_core.scripts.import_resources:Skipping /organisation.
ERROR:ZODB.Connection:Couldn't load state for adhocracy_core.resources.pool.Pool 0x020b
Traceback (most recent call last):
  File "/home/caroline/www/adhocracy3/eggs/ZODB-4.1.0-py3.4.egg/ZODB/Connection.py", line 871, in setstate
    self._setstate(obj)
  File "/home/caroline/www/adhocracy3/eggs/ZODB-4.1.0-py3.4.egg/ZODB/Connection.py", line 925, in _setstate
    self._reader.setGhostState(obj, p)
  File "/home/caroline/www/adhocracy3/eggs/ZODB-4.1.0-py3.4.egg/ZODB/serialize.py", line 634, in setGhostState
    state = self.getState(pickle)
  File "/home/caroline/www/adhocracy3/eggs/ZODB-4.1.0-py3.4.egg/ZODB/serialize.py", line 627, in getState
    return unpickler.load()
  File "/home/caroline/www/adhocracy3/eggs/zope.interface-4.1.2-py3.4-linux-x86_64.egg/zope/interface/declarations.py", line 488, in Provides
    spec = ProvidesClass(*interfaces)
  File "/home/caroline/www/adhocracy3/eggs/zope.interface-4.1.2-py3.4-linux-x86_64.egg/zope/interface/declarations.py", line 456, in __init__
    Declaration.__init__(self, *(interfaces + (implementedBy(cls), )))
  File "/home/caroline/www/adhocracy3/eggs/zope.interface-4.1.2-py3.4-linux-x86_64.egg/zope/interface/declarations.py", line 65, in __init__
    Specification.__init__(self, _normalizeargs(interfaces))
  File "/home/caroline/www/adhocracy3/eggs/zope.interface-4.1.2-py3.4-linux-x86_64.egg/zope/interface/declarations.py", line 840, in _normalizeargs
    _normalizeargs(v, output)
  File "/home/caroline/www/adhocracy3/eggs/zope.interface-4.1.2-py3.4-linux-x86_64.egg/zope/interface/declarations.py", line 839, in _normalizeargs
    for v in sequence:
TypeError: 'type' object is not iterable
Traceback (most recent call last):
  File "bin/import_resources", line 114, in <module>
    sys.exit(adhocracy_core.scripts.import_resources.import_resources())
  File "/home/caroline/www/adhocracy3/src/adhocracy_core/adhocracy_core/scripts/import_resources.py", line 57, in import_resources
    _import_resources(env['root'], env['registry'], args.filename)
  File "/home/caroline/www/adhocracy3/src/adhocracy_core/adhocracy_core/scripts/import_resources.py", line 66, in _import_resources
    if _resource_exists(expected_path, root):
  File "/home/caroline/www/adhocracy3/src/adhocracy_core/adhocracy_core/scripts/import_resources.py", line 91, in _resource_exists
    find_resource(context, expected_path)
  File "/home/caroline/www/adhocracy3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/traversal.py", line 107, in find_resource
    D = traverse(resource, path)
  File "/home/caroline/www/adhocracy3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/traversal.py", line 342, in traverse
    return traverser(request)
  File "/home/caroline/www/adhocracy3/eggs/pyramid-1.5.2-py3.4.egg/pyramid/traversal.py", line 711, in __call__
    next = getitem(segment)
  File "/home/caroline/www/adhocracy3/src/substanced/substanced/folder/__init__.py", line 323, in __getitem__
    return wrap_if_broken(self.data[name])
  File "/home/caroline/www/adhocracy3/src/substanced/substanced/util/__init__.py", line 637, in wrap_if_broken
    if is_broken(resource):
  File "/home/caroline/www/adhocracy3/src/substanced/substanced/util/__init__.py", line 624, in is_broken
    return IBroken.providedBy(resource)
  File "/home/caroline/www/adhocracy3/eggs/zope.interface-4.1.2-py3.4-linux-x86_64.egg/zope/interface/interface.py", line 97, in providedBy
    spec = providedBy(ob)
  File "/home/caroline/www/adhocracy3/eggs/zope.interface-4.1.2-py3.4-linux-x86_64.egg/zope/interface/declarations.py", line 757, in providedByFallback
    r = ob.__providedBy__
  File "/home/caroline/www/adhocracy3/eggs/ZODB-4.1.0-py3.4.egg/ZODB/Connection.py", line 871, in setstate
    self._setstate(obj)
  File "/home/caroline/www/adhocracy3/eggs/ZODB-4.1.0-py3.4.egg/ZODB/Connection.py", line 925, in _setstate
    self._reader.setGhostState(obj, p)
  File "/home/caroline/www/adhocracy3/eggs/ZODB-4.1.0-py3.4.egg/ZODB/serialize.py", line 634, in setGhostState
    state = self.getState(pickle)
  File "/home/caroline/www/adhocracy3/eggs/ZODB-4.1.0-py3.4.egg/ZODB/serialize.py", line 627, in getState
    return unpickler.load()
  File "/home/caroline/www/adhocracy3/eggs/zope.interface-4.1.2-py3.4-linux-x86_64.egg/zope/interface/declarations.py", line 488, in Provides
    spec = ProvidesClass(*interfaces)
  File "/home/caroline/www/adhocracy3/eggs/zope.interface-4.1.2-py3.4-linux-x86_64.egg/zope/interface/declarations.py", line 456, in __init__
    Declaration.__init__(self, *(interfaces + (implementedBy(cls), )))
  File "/home/caroline/www/adhocracy3/eggs/zope.interface-4.1.2-py3.4-linux-x86_64.egg/zope/interface/declarations.py", line 65, in __init__
    Specification.__init__(self, _normalizeargs(interfaces))
  File "/home/caroline/www/adhocracy3/eggs/zope.interface-4.1.2-py3.4-linux-x86_64.egg/zope/interface/declarations.py", line 840, in _normalizeargs
    _normalizeargs(v, output)
  File "/home/caroline/www/adhocracy3/eggs/zope.interface-4.1.2-py3.4-linux-x86_64.egg/zope/interface/declarations.py", line 839, in _normalizeargs
    for v in sequence:
TypeError: 'type' object is not iterable
```

**Comment by xi** [comment]
@local-girl I restored my original branch and pushed your additions to a separate one ([2015-09-tb-pcompass-request-service-style](https://github.com/liqd/adhocracy3.mercator/tree/2015-09-tb-pcompass-request-service-style)) I would like to get this merged soon so I think it is better to have them in separate pull requests.

**Comment by nidico** [comment]
We need my changes from 3ca4978dd743e11571df01df41254140c6568fec and 0aa73d427b1dd46a797560fa950c9f4b2a85f3b4 (now in the new branch) before merging to master, otherwise it won't work.

**Comment by local-girl** [comment]
I've had a look through the code & merged master. I'm not an expert but everything looks OK and seems to work so I am merging.

**Comment by xi** [comment]
The commits I had previously removed have sneaked in again. I Will review them ASAP.

**Comment by xi** [comment]
I added a small fixup in #1699 and some possible refactoring issues (#1694, #1698). Apart from that, this all looks fine.

**Pull request merged**
