### PR TITLE
refactor rate

### PR DESCRIPTION
**Pull request by xi**
this refactors the frontend rate module and contains a reimplementation of #623. It also adds the like button at the bottom of the mercator proposal detail page.

### CODE REVIEW

**Comment by nidico** [comment]
LGTM. However, I don't receive updates from the websocket server on cast, although the item is registered.

**Comment by nidico** [comment]
For the MercatorProposal two rate directives synchronisation, we also need a soution for the situation in which the current user hasn't posted a rate *item* yet. In this case there are are no websocket registered; if an item is finally posted through one rate directive is pressed the other rate directive doesn't notice. We probably want some local event handling.

**Comment by xi** [comment]
I solved the problem by adding a local `adhRateEventHandler` service that syncs the directives locally.

**Comment by nidico** [comment]
Works nicely!

**Pull request merged**
