### PR TITLE
Add Logbook to mercator proposal

### PR DESCRIPTION
**Pull request by xi**

### CODE REVIEW

**Comment by nidico** [comment]
Can you please rebase / merge?

**Comment by MagdaN** [comment]
As this is not ready yet, we decided to keep on working in this branch. So, please do not merge, yet.

**Comment by MagdaN** [comment]
edit does not work due to the following error: 

description: "This Resource does not provide interface adhocracy_core.sheets.image.IImageMetadata"location: "body"name: "data.adhocracy_core.sheets.image.IImageReference.picture"

**Comment by MagdaN** [comment]
@local-girl :  looks good - just one little thing: in editing mode there should also be the select dropdown for the title just like in creation. Do you think you can change that or should I do it?

**Comment by local-girl** [comment]
I can

**Comment by MagdaN** [comment]
This works except for the two errors:
1) cant create two entries with the same title -> this is being taken care of by this: #1401 
2) cant edit document (also true for spd documents) -> "This Resource does not provide interface adhocracy_core.sheets.image.IImageMetadata"location: "body"name: "data.adhocracy_core.sheets.image.IImageReference.picture", see issue: https://github.com/liqd/adhocracy3.mercator/issues/1397

**Comment by nidico** [comment]
#1401 is merged - removing "on hold" label.

**Comment by MagdaN** [comment]
this should work now - let me know if you need a db for testing

**Comment by MagdaN** [comment]
@xi there is still one problem: when you go to a proposal without a winning badge and add @blog to the url, you see 'No entries yet' but I guess it would be better to get a 404.

**Comment by xi** [comment]
Already noticed that. I have an idea how to fix this. Will work on that today.

**Comment by MagdaN** [comment]
Yeah, I started working on that, but could not find a good way for it

**Comment by xi** [comment]
Seems to work fine. I also tested as a normal user.

**Comment by MagdaN** [comment]
looks good to me as well

**Pull request merged**
