### PR TITLE
Adding SPD files

### PR DESCRIPTION
**Pull request by local-girl**
I ran the file:///home/caroline/www/adhocracy3/docs/build/html/development.html#create-scaffold-for-extension-packages except the bower bit 

Not sure what else to do !

### CODE REVIEW

**Comment by MagdaN** [comment]
I get the following error: 

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at modules (/home/magda/Documents/dev/adhocracy3/src/spd/spd/build/js/mkResources.js:73:27)
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)
resources: Non zero exit code (8) while running command

**Comment by local-girl** [comment]
Me too !

**Comment by MagdaN** [comment]
@nidico @joka: what could be the problem here?

**Comment by xi** [comment]
For me this works now. I had to also create a backend package and modify some other files. Documentation is included.

Note that I was not completely sure about the supervisor config in `buildout-spd.cfg` because that is also inconsistent for the other customizations.

Could please someone else review test this?

**Comment by nidico** [comment]
Works.

**Pull request merged**
