### PR TITLE
Bring meinberlin frontend inline with changes proposed in #1618 (breaking changes to embed API!)

### PR DESCRIPTION
**Pull request by xi**
*implements #1618 for the frontend*

this contains the following breaking changes to the embed API:

-   "kiezkassen" context is renamed to "kiezkasse"
-   "burgerhaushalt" context is renamed to "buergerhaushalt"
-   "mein-berlin-bplaene-proposal-embed" widget is renamed to "meinberlin-bplan-proposal-embed"

The old names still work via an alias system I added to the adhEmbedProvider. However, I would like to have the following deprecation procedure:

-   update the servers
-   inform all embedders about the changes
    -   include updated embed snippets
    -   give them a deadline (~3 month?) until which they can update their embed code
-   remove the aliases some time after the deadline

We need to coordinate this with project management. @slomo, @rukala: what do you think?

### CODE REVIEW

**Comment by slomo** [comment]
Why isn't `buergerhaushalt` and `kiezkasse` named `meinberlin-*` ?

I mean after all they are as meinberlin specific as bplan. Or is the difference in naming due to their difference in embed (bplan a single proposal while the other are context embeds).

**Comment by xi** [comment]
> Why isn't buergerhaushalt and kiezkasse named meinberlin-* ?

Good point. This is kind of unrelated, but when we need to inform embedders about breaking changes we could just as well cover this issue at the same time.

I guess we never thought about naming conventions for contexts. Without much thought I would think namespacing them is a good idea.

**Comment by slomo** [comment]
So since this is backwards compatible. I see no issues it being merged (apart of my missing forntend expertise).

Afterwards we can decide on name spacing and afterwards inform our customers.

**Comment by xi** [comment]
I updated the unit tests

**Comment by nidico** [comment]
LGTM.

**Pull request merged**
