### PR TITLE
Make URL clickable where available fixes #911

### LINKED ISSUE #911: Org URL not clickable in detail view

### PR DESCRIPTION
**Pull request by local-girl**

### CODE REVIEW

**Comment by xi** [comment]
AFAIK, website is optional. So there should only be a link if it has been set.

Additionally, the link should also be in the "planned_nonprofit" and "planned_nonprofit" cases.

**Comment by xi** [comment]
> AFAIK, website is optional. So there should only be a link if it has been set.

To clearify: It seems like `ngHref` does not create a `href` attribute if the value is empty. But the `<a>` tag is still there resulting in wrong styling.

**Comment by local-girl** [comment]
Fixed up in 7775fa6

**Comment by xi** [comment]
I think we should still use `ngHref` in this case (see also #914)

**Comment by local-girl** [comment]
fixup 0a72f7d

**Comment by xi** [comment]
LGTM

**Pull request merged**
