### PR TITLE
Run linters on travis

### PR DESCRIPTION
**Pull request by xi**
this extends `bin/check_code` to be able to check all files, not only the staged ones. This is then used to run the linters on travis.

Unfortunately, flake8 reports many issues. I guess this is due to wrong config. Can someone tell what needs to be changed?

### CODE REVIEW

**Comment by xi** [comment]
There also seems to be an issue with tslint which should be fixed by merging #1450

**Comment by xi** [comment]
I saw that most issues are for lines with a `# noqa` comment. According to the [pep8 docs](https://pep8.readthedocs.org/en/latest/intro.html#error-codes), `# noqa` only disables few rules. We can either disable the rules completely or disable linting for the whole file (using `# flake8: noqa`).

Site note: `# flake8: noqa` is used in some places at the end of the line. In this case, it also disables flake8 for the complete file. So I would suggest to move these comments to their own lines on the top of the file.

**Comment by xi** [comment]
I removed the linters from travis again. So now we can merge this PR, fix all open issues and then add it again.

**Comment by pallix** [comment]
So is the plan to check the whole code on each PR with travis? I guess it will make checks slower but relative to the time taken by the acceptance tests it's probably acceptable.

**Comment by pallix** [comment]
LGTM

**Pull request merged**
