### PR TITLE
2015 05 jk refactor messaging

### PR DESCRIPTION
**Pull request by joka**

### CODE REVIEW

**Comment by pallix** [comment]
I get a build problem:

```
undefined:0

^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at modules (/home/alphonse/projects/adhocracy3.mercator/src/mercator/mercator/build/js/mkResources.js:73:27)
```

**Comment by pallix** [comment]
Maybe merge master?

**Comment by joka** [comment]
> Maybe merge master?

done and fixed (the `resources` buildout part was not working because pyramid_mail was not setup in etc/noserver.ini)

**Comment by pallix** [comment]
Acceptance tests related to mailing work, pyfunc and pyunit also.

**Pull request merged**
