### PR TITLE
Updated button styling

### PR DESCRIPTION
**Pull request by xi**
extracted from #1071.

@local-girl, can you give some more details on why this change was made?

### CODE REVIEW

**Comment by local-girl** [comment]
The rounded corners were in the design and cta-2 was just awful in meinberlin so I tidied it up. Sorry i should have written a summary!

**Comment by xi** [comment]
merging myself because the code was actually written by @local-girl

**Comment by xi** [comment]
On second thought, the rounded corners should not be implemented via child selectors but as a modifier.

**Comment by local-girl** [comment]
I'll re-consider this in another branch. It's not clear in what scenarios the buttons have rounded corners.

**Comment by xi** [comment]
Its not too important though.

**Pull request merged**
