### PR TITLE
refactor image scaling API CHANGE

### PR DESCRIPTION
**Pull request by joka**
REST API CHANGE:

-  add image resize download URLs to ImageMetadata sheett ( see docs/asset_and_images.rst)
   rm  download URL suffix (../detail, /thumbnail, ./raw )
-  IAsset/Image Metadata sheet is required for put and post request (before optional for put request)
- rm `raw` download for Images, needless and migth be was target for DOS attacks
- Image URLs are stable now and  cached forever in browser, 
- Fix bug: Displayed images are not updated at once after editing.

INTERNAL Refactoring::

- rm resource metadata image_sizes/mime_type_validator, use colander schema instead.(SRP)
- new asset download implementation / modeling (simplify, SRP)

MISSING: 

- [x] adapt frontend to changed ImageMetadata sheet

### CODE REVIEW

**Comment by joka** [comment]
The REST API changes are discussed with @nico, but feel free to propose different solutions.
(For example we could also make Images versionable to have stable image resize download urls)

After changing an Image, the old image resize donwloads are not deleted to prevent broken links.
Do you think this is important or should we just delete them to save database space?

**Comment by xi** [comment]
I would like to go through the API changes one by one to see whether the frontend needs adaption. @joka when do you have time for that?

**Comment by pallix** [comment]
Some tests are failing otherwise LGTM

**Comment by joka** [comment]
> I would like to go through the API changes one by one to see whether the frontend needs adaption. @joka when do you have time for that?

around 12:00 today?

**Comment by joka** [comment]
> I would like to go through the API changes one by one to see whether the frontend needs adaption. @joka when do you have time for that?
> around 12:00 today?

a you still have your workshop on wednesday.
I'm in holiday now. This man change is just how the frontend retrieves the urls to download resized images:.  Have a look at  assets_and_images.rst

**Comment by nidico** [comment]
I started on the frontend changes in branch `2015-09-jk-refactor-image-scaling-frontend` yesterday. It's not working yet, however the intention should be clear if someone wants to adopt it.

**Comment by joka** [comment]
Adding image reference to users users is done: https://github.com/liqd/adhocracy3.mercator/pull/1805

**Comment by dwt** [comment]
I've finished the fronted changes so the existing projects will work with this again. Ready to merge I'd say.

**Comment by joka** [comment]
testet with mercator and mein berlin alexanderplatz

**Comment by MagdaN** [comment]
added a small bugfix, tested it with mercator, works

**Comment by dwt** [comment]
@MagdaN thanks! Seems I completely missed this. :)

**Comment by nidico** [comment]
Let's merge this.

**Pull request merged**
