### PR TITLE
Limit listing size, add show-more button (fixes #710)

### LINKED ISSUE #710: Restrict initial listing size, dynamically load more content
We currently always load all proposals in the main listing. This doesn't scale.

We need to allow to limit the initial list size and load more content on demand (see twitter etc.) or do pagination.

Design-wise, I'm unsure how "load-more" goes together with facetted search.

### LINKED ISSUE #936: Bad performance on long user list
When I visit https://advocate-europe.eu/en/idea-space#!/r/principals/users/ adhocracy gets really slow. That might be due to the 3150 users.

### PR DESCRIPTION
**Pull request by nidico**
See individual commits.

Missing:

- [x] UI and translations for show-more button.
- [ ] Automatic load-more when scrolling to the bottom (optional in my opinion)
- [ ] Backend unittest coverage
- [x] Extend `rest_api.rst` doctest

This should also fix #936.

### CODE REVIEW

**Comment by xi** [comment]
Frontend code looks ok. I tested it locally and seems to work fine. I also talked to the designers and will add some CSS to this pull request.

**Comment by joka** [comment]
i had a rough look at the backend, its ok.
Can you add a simple functional test in rest_api.rst? 
Then i will fill fix the unit test coverage.

**Comment by xi** [comment]
I will work on the functional test.

**Comment by joka** [comment]
ok, looks good to me

**Comment by nidico** [comment]
@xi: What should be written on the button?

**Comment by nidico** [comment]
Backend unit tests will be done later.

**Pull request merged**
