### PR TITLE
Adding pre-wrap styles to user ediable text

### PR DESCRIPTION
**Pull request by local-girl**
Fixes lack of text-wrapping in user entered sections. Tested in mercator, SPD & MeinBerlin

### CODE REVIEW

**Comment by nidico** [comment]
This would also apply to the `p` items generated by the `adh-parse-markdown` directive. This would encourage users to write incorrect markdown (e.g. assume that a single line-break indeed breaks the line).

Can you suppress that?

**Comment by local-girl** [comment]
This was deliberate, i tested it with markdown and it seemed to work

**Comment by local-girl** [comment]
OK fixed

**Comment by local-girl** [comment]
continued in #1410

**Pull request closed without merging**
