### PR TITLE
fix comments (fixes #804)

### LINKED ISSUE #804: Comment rate + edit broken
Steps to reproduce:

-  create a comment
-  rate that comment
-  edit that comment

Expected result:

-  rate counter shows 1

Actual result:

-  rate counter shows 0

### PR DESCRIPTION
**Pull request by xi**
continued from #838.

### CODE REVIEW

**Comment by nidico** [comment]
Unfortunately, this systematically doesn't work for me. Haven't investigated this any further yet, might very well be a race condition.

**Comment by xi** [comment]
I guess this depends on #845.

**Comment by nidico** [comment]
This was my thought as well. I just merged #845, which looks good for me this time... Can you do a rebase?

**Comment by nidico** [comment]
Indeed. I'll rebase, push-force and merge.

**Pull request merged**
