### PR TITLE
2015 04 jk run all tests

### PR DESCRIPTION
**Pull request by joka**
Problem:

   * no script to run all tests
   * documentation how to run tests complicated/broken
   * broken tests because nobody runs them (happend twice in python test)

Proposal:
    
   * user polytester to run all python and available javascript/acceptance tests
   * simplify buildout config to create testscripts and add dependencies to python path
   * updated documentation

Example: 

    run:
    
        bin/polytester -c test.yml
    
    restrict tests:
    
        bin/polytester -c test.yml pyunit
    
    enable verbose output:

           bin/polytester -v -c test.yml pyunit

### CODE REVIEW

**Comment by joka** [comment]
@nidico  @pallix  can you give some feedback?

**Comment by pallix** [comment]
I had to specify tests with `--config` with polytester 1.2.0.
It seems the default file is named `tests.yml`, we can rename `test.yml` in `tests.yml`

**Comment by joka** [comment]
> It seems the default file is named tests.yml, we can rename test.yml in tests.yml

polytest did also look in  .bin/ directory instead of ./ for tests.yml

**Comment by joka** [comment]
added new pull request #1031

**Pull request closed without merging**
