### PR TITLE
 reduce logging noise backend

### PR DESCRIPTION
**Pull request by joka**
- less logging to shell when running backend  tests
- decrease logging level for "Problem connection to Websocket server" error from warning to info
- don't include 'pyramid_exclog' (force logging of all python exceptions), this only makes sense for productive installations.

### CODE REVIEW

**Comment by nidico** [comment]
Please merge / rebase master.

**Comment by joka** [comment]
> Please merge / rebase master.

done

**Comment by pallix** [comment]
`TestMercatorWorkflow.test_participate_can_create_and_update_proposal_per_batch` is failing

**Comment by joka** [comment]
> TestMercatorWorkflow.test_participate_can_create_and_update_proposal_per_batch is failing

oh no, this is master, maybe related to  e8aaac010aee9f5d91fd7f9fd4e2be6f1ca29102

**Comment by joka** [comment]
> TestMercatorWorkflow.test_participate_can_create_and_update_proposal_per_batch is failing
> oh no, this is also in master, maybe related to e8aaac0

fixed

**Pull request merged**
