### PR TITLE
check register permissions

### PR DESCRIPTION
**Pull request by xi**
This only shows register UI if registration is allowed. Activation is still available.

### CODE REVIEW

**Comment by nidico** [comment]
Is there already an easy way to change the permission to register in the backend in order to test that?

**Comment by xi** [comment]
> Is there already an easy way to change the permission to register in the backend in order to test that?

Don't know.

**Comment by xi** [comment]
I just merged #1620 so this can now be tested with the kit package.

**Comment by nidico** [comment]
This needs a merge / rebase.

**Pull request merged**
