### PR TITLE
2015 03 mn add geofield to kiezkassen proposal

### PR DESCRIPTION
**Pull request by MagdaN**

### CODE REVIEW

**Comment by MagdaN** [comment]
Please review this by building meinberlin and go to link: http://localhost:6551/embed/mein-berlin-create

**Comment by MagdaN** [comment]
This is ready for review. When this is done the css styles can be applied. Should that happen in the same branch?

**Comment by MagdaN** [comment]
@local-girl: could you please do the styling as soon as this is reviewed

**Comment by xi** [comment]
Looks good to me. I made some adjustments to increase readability.

@local-girl can you please do styling in a separate branch? Especially the inline CSS should be removed.

**Pull request merged**
