### PR TITLE
Improve rest api doc

### PR DESCRIPTION
**Pull request by pallix**

### CODE REVIEW

**Comment by pallix** [comment]
Fixes #1418

**Comment by xi** [comment]
Looks good to me, except for one detail: In rest_api.rst you reference `IMetadata`. But the actual definition is at `MetadataSchema`. Is that intended?

**Comment by pallix** [comment]
The interface is used as a marker and the `MetadataSchema` for validation. We can say the concrete type is opaque and of type `IMetadata` so it's correct.

**Comment by xi** [comment]
It is consitent with the existing documentation. That's fair enough for me.

**Pull request merged**
