### PR TITLE
remove needless test fixtures, update pep257/pep8

### PR DESCRIPTION
**Pull request by joka**
- rm needless splinter (test browser) test fixtures
- update pytest (new option to run only failed tests)
- update pep8/pep257 (news: no new line above class docstring, no sourrounding spaces in docstring)
- run autopep8 --aggressive for all files
- check pep8/pep257 for all files

### CODE REVIEW

**Comment by pallix** [comment]
`run autopep8 --aggressive for all files` didn't work very well the access control matrix :-).

**Comment by joka** [comment]
> run autopep8 --aggressive for all files didn't work very well the access control matrixes :-).

Matrix restored. HAIL  the corporation.

**Comment by pallix** [comment]
You need to merge master

**Comment by joka** [comment]
> You need to merge master

done and tests pass locally, i merge this now.

**Pull request merged**
