### PR TITLE
set same creation/modification date for modified resources in transaction

### PR DESCRIPTION
**Pull request by joka**

### CODE REVIEW

**Comment by joka** [comment]
@local-girl needs this

**Comment by joka** [comment]
ups, one failing tests

**Comment by ChristianSi** [comment]
The failing test is unrelated. I don't now how it came into master, but I fixed it in #790.

**Comment by nidico** [comment]
This doesn't work for me: A batch created comment version still has a newer `creation_date` than the corresponding item, which has been created during the same request. Reopening #770.

**Pull request merged**
