### PR TITLE
refactor workflow assignment  REST API CHANGE

### PR DESCRIPTION
**Pull request by joka**
We will make intensive use of workflow for the parotu agend s1 proceess. 
Before that I want to refactor the workflow assignment to reduce  needless code in the backend and partly in the frontend.

## API Changes IWorkflowAssignment sheet

- rm field workflow `states_order` , add `inital_state` (not used anyway, more explicit this way)

-  make it a generic sheet to display/edit workflow meta data. 
   No more fields for every workflow state, instead on field `state_data` with a list of dictionaries to store   instance specific state meta data (see `docs/workflows.rst`)

- add it to all IPool and ISimple resource type (default: no workflow is assigned)

- rm workflow.ISample sheet

- rm workflow.IStandard sheet

- rm sheets adhocracy_meinberlin.sheets.bplan/kiezkassse.IWorkflowAssignment

- rm sheet workflow.IStandard from resource type alexanderplatz.IProcess

- rm sheet adhocracy_mercator.sheets.mercator.IWorkflowAssignment 

- rm sheet adhcoracy_spd.sheets.digital_leben.IWorkflowAssignment 

## SCRIPTS Changes:

-  explicit set intermediate states for `set_workflow_state` script, example:
    `bin/set_workflow_state /etc/backend.ini /process draft announced participate`

## INTERNAL Changes:

- add resource metadata entry `workflow_name` to assign a workflow to a
ressource

- rn `setup_workflow` to 'transition_to_states' (more descriptive)

- `transition_to_states` :  initalize workflow for context only if needed (otherwise this may have
bad side effects)

- `transition_to_states`:  initalize workflow for context only if needed (otherwise this may have
bad side effects)

- use registry.content method `get_workflow` to retrieve the workflow for an resource instance (reduce complexity)

## TODO:

- frontend adaption

### CODE REVIEW

**Comment by xi** [comment]
> No more fields for every workflow state, instead on field state_data with a list of dictionaries to store instance specific state meta data (see docs/workflows.rst)

Just to be sure: This means that the same information is still available, only in another place, right?

**Comment by pallix** [comment]
It would be good to have a ```--reset``` option on the script, to reset the workflow. This would re-allow to to from, for instance, 'result' phase to 'draft'.

**Comment by pallix** [comment]
@joka please merge master

**Comment by pallix** [comment]
@slomo needs to update the prod scripts

**Comment by pallix** [comment]
Very cool. LGTM.

**Comment by pallix** [comment]
Can be merged once @MagdaN is done with the review

**Comment by MagdaN** [comment]
I tried to build the mercator buildout - which worked and after creating a new Database the workflowstate was set to 'participate' but I could not run the set_workflow_state and also in the frontend api I could see that there now is a list 'state_data' but this list was emty

**Comment by MagdaN** [comment]
@joka @pallix can you please mege master

**Comment by pallix** [comment]
I need to update how the `set_workflow_state` script works, with @slomo suggestions

**Comment by pallix** [comment]
TODO: update installation.rst

**Comment by xi** [comment]
> I need to update how the `set_workflow_state` script works, with @slomo suggestions

Will be done in a separate branch

**Pull request merged**
