### PR TITLE
Update badge assignment UI

### PR DESCRIPTION
**Pull request by xi**
This expands on #1692. I talked to some designers and we decided to change the top level dropdown to a list of badges. I also added the UI to pcompass and fixed translation.

@local-girl could you please fix the styling?

### CODE REVIEW

**Comment by local-girl** [comment]
@xi I improved the styling including core styles please review

**Comment by local-girl** [comment]
ok good to go ? @xi

**Comment by xi** [comment]
Someone still needs to review my commits.

**Comment by nidico** [comment]
LGTM.

**Pull request merged**
