### PR TITLE
spd workbench

### PR DESCRIPTION
**Pull request by xi**
This implements the mercator workbench and the communication with the backend. Sorry for the large pull request.

Note that this is rebased against #1292 so that should be merged first.

Also note that due to a backend bug, the paragraphs are scrambled by the backend. Among other things, this breaks editing.

I did not yet spend much thought on workflow. So there might be some more work to do.

### CODE REVIEW

**Comment by MagdaN** [comment]
@xi @local-girl how can I test it?

**Comment by local-girl** [comment]
As far as I know

**Comment by xi** [comment]
> how can I test it?

Simply build spd and go to `/r/adhocracy`

**Comment by xi** [comment]
With the merge of #1298 we probably need to adjust this to use the right process type

**Comment by MagdaN** [comment]
cannot edit documents, error is: "No fork allowed - The auto update tried to create a fork for: /adhocracy/Mein_Dokument/VERSION_0000003 caused by isheet: adhocracy_core.sheets.document.IDocument field: elements with old_reference: /adhocracy/Mein_Dokument/PARAGRAPH_0000001/VERSION_0000001 and new reference: /adhocracy/Mein_Dokument/PARAGRAPH_0000001/VERSION_0000002. Try another root_version."

**Comment by xi** [comment]
> cannot edit documents

As described in the OP, editing is not possible due to a backend bug.

**Comment by MagdaN** [comment]
Looks good to me, except for the missing styling of the list item and the edit-error. @xi Should that be fixed in a new branch after this one has been merged?

**Comment by xi** [comment]
> except for the missing styling of the list item

That is done in #1300

**Comment by MagdaN** [comment]
@xi : cann you remove the merge conflict

**Pull request merged**
