### PR TITLE
Prevent creating empty first versions within batch request (save 10% database size)

### PR DESCRIPTION
**Pull request by joka**
depends on  #1647

API EXTENSION:

- Update first version instead of creating a new version within a batch request. This  prevents creating an empty first version for every item we create.

- migration script to delete exsiting first versions without any data.

UPGRADE NOTE:

Long running migration script that delets resources, have a backup by hand. @slomo .

### CODE REVIEW

**Comment by pallix** [comment]
Comment above, LGTM otherwise.

**Comment by xi** [comment]
Does this require changes in the frontend?

**Comment by joka** [comment]
> Does this require changes in the frontend?

no, but after migration we should do a quick manual test if commenting works.

**Comment by joka** [comment]
@pallix  I fixed the docs/comments and rebased master, can you merge?

**Pull request merged**
