### PR TITLE
display badges in document

### PR DESCRIPTION
**Pull request by MagdaN**

### CODE REVIEW

**Comment by MagdaN** [comment]
@local-girl, could you add the badge styles?

**Comment by local-girl** [comment]
Ja

**Comment by MagdaN** [comment]
In chrome and firefox the writing seems to be a little bit stuck to the top?

badges

**Comment by MagdaN** [comment]
@local-girl could you check please - I think one minor css change is needed for the distance between title and batch. Let me know if you need a db

**Comment by local-girl** [comment]
LGTM if it LGTY

**Pull request merged**
