### PR TITLE
2015 04 cc moving columns styling

### PR DESCRIPTION
**Pull request by local-girl**

### CODE REVIEW

**Comment by local-girl** [comment]
Still working on it

**Comment by xi** [comment]
Looks good. Unfortunately there are already new designs.

**Comment by local-girl** [comment]
Added styles as per new designs. List / map switcher is there even though it has no functionality waiting for merge of #1015

**Comment by xi** [comment]
Currently this cannot autmatically be merged. As this has become quite a long list of commits  I would be happy if you could rebase.

**Comment by local-girl** [comment]
Continued on #1030

**Pull request closed without merging**
