### PR TITLE
Add resource for policycompass

### PR DESCRIPTION
**Pull request by pallix**

### CODE REVIEW

**Comment by xi** [comment]
I am not sure if it is a good idea to call this a "policycompass process" rather than a "policycompass request process".

**Comment by pallix** [comment]
@joka by the way, proposals from core can't be posted to the process in core [1], which is why I created this resource. Seems strange to me.

Maybe we need core process with a standard workflow having core proposals. This could cause a problem for the tests since they don't set the workflow state at all.

[1] which has the 'sample' workflow, not standard.

**Comment by pallix** [comment]
@xi you want `IRequestProcess` and `request_process_meta` in the code instead?

**Comment by xi** [comment]
> you want `IRequestProcess` and `request_process_meta` in the code instead?

I am not sure about `request_process_meta`, but I would rather like to have `adhocracy_pcompass.resources.request.IProcess` than `adhocracy_pcompass.resource.pcompass.IRequestProcess`. (Like in meinberlin)

**Comment by pallix** [comment]
Done.

**Comment by nidico** [comment]
LGTM.

**Pull request merged**
