### PR TITLE
2015 07 mn add alexanderplatzpolygon

### PR DESCRIPTION
**Pull request by MagdaN**

### CODE REVIEW

**Comment by MagdaN** [comment]
@pallix I added the alexanderplatz geojson and also added a function to load this. Is this helpful? If yes, I  can refactor the whole script (also the other functions)

**Comment by pallix** [comment]
Is it not possible to just reuse the `import_resources` script?

**Comment by MagdaN** [comment]
@pallix ah I did not think of this - will try

**Comment by pallix** [comment]
simpler solution in #1447

**Pull request closed without merging**
