### PR TITLE
use catalog search  to get  user

### PR DESCRIPTION
**Pull request by joka**
API EXTENSION:

- add search index 'user_name' (to sort user by login name)

INTERNAL:

- refactor to speed up login/activation of users

MANUAL MIGRATION NEEDED:

Restart adhocracy, then reindex all users (@slomo):

    bin/sd_reindex  -c adhocracy etc/development.ini -p "/principals/users"

### CODE REVIEW

**Comment by slomo** [comment]
@joka How dangerous would it be to always have that reindex step in the deployment (I am not really into manual deployment steps)

**Comment by slomo** [comment]
Nevermind just saw that this is a really specialised reindex.

**Comment by joka** [comment]
> @joka How dangerous would it be to always have that reindex step in the deployment (I am not really into manual deployment steps)

I tried to add an automatic migrations step, but this is not easy.

**Comment by joka** [comment]
> @joka How dangerous would it be to always have that reindex step in the deployment (I am not really into manual deployment steps)

reindexing all resources is not dangerous, but may take quite a lot time. So we should do it only when needed

**Comment by pallix** [comment]
@joka some tests are failing

**Comment by pallix** [comment]
LGTM, except failing tests

**Comment by joka** [comment]
> @joka some tests are failing

The failing acceptence test is in master and might be related 
The acceptance test are not running on my local machine for some days, so unfortunately did not noticed this.

**Pull request merged**
