### PR TITLE
Allow import user script to modify user names

### PR DESCRIPTION
**Pull request by pallix**
Also it updates user if either the login or the email already exists (previously the check was done only on the login name)

### CODE REVIEW

**Comment by pallix** [comment]
@slomo you can update user names with this script once merged

**Comment by pallix** [comment]
Fixes #1382

**Comment by joka** [comment]
one backend test is failing

**Comment by pallix** [comment]
Tests running ok after merge of master

**Comment by pallix** [comment]
@joka can you merge?

**Pull request merged**
