### PR TITLE
2015 05 cc tabs extra features

### PR DESCRIPTION
**Pull request by local-girl**
Some extra options for tabs. Ability to add extra classes + "Closed by default"

### CODE REVIEW

**Comment by local-girl** [comment]
Just updating docs !

**Comment by local-girl** [comment]
Please merge this before #1070

**Comment by xi** [comment]
Looks great!

Just one minor thing: When you open a tab in a closed-by-default tabset for the first time, the transition is not smooth. I will look at that in a separate branch.

**Comment by xi** [comment]
> Just one minor thing: When you open a tab in a closed-by-default tabset for the first time, the transition is not smooth. I will look at that in a separate branch.

Fixed in e61af09

**Pull request merged**
