### PR TITLE
2015 04 cc moving columns styling+1

### PR DESCRIPTION
**Pull request by local-girl**
Continued from #1020

### CODE REVIEW

**Comment by xi** [comment]
Looks great! See  my comments above. Also, the user columns need to be updated, too.

**Comment by local-girl** [comment]
Don't know what `moving-column-expand` is please explain tomorrow

**Comment by local-girl** [comment]
I added the tabs to user space but without text for now as this is core, not sure how to target meinberlin or if we need to

**Comment by xi** [comment]
> I added the tabs to user space but without text for now as this is core, not sure how to target meinberlin or if we need to

I had thought that we had two versions of these columns.

I think it is not urgent. But I see two ways in which this could be done:

-   overwrite column templates in meinberlin
-   add text in template, hide via CSS in core

**Comment by xi** [comment]
> Don't know what `moving-column-expand` is please explain tomorrow

It is the class you added in 95a5e6a

**Comment by local-girl** [comment]
OMG I suck, doing this now

**Comment by local-girl** [comment]
It is only referenced in the meinberlin _moving_columns_theme.scss - does it need to be in mercator?

**Comment by local-girl** [comment]
Done

**Pull request merged**
